// app/(relative-tabs)/index.tsx
import { Ionicons } from "@expo/vector-icons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { LinearGradient } from "expo-linear-gradient";
import * as Location from "expo-location";
import { useRouter } from "expo-router";
import {
  arrayUnion,
  collection,
  doc,
  getDoc,
  onSnapshot,
  query,
  serverTimestamp,
  updateDoc,
  where
} from "firebase/firestore"; // Bỏ onSnapshot ở đây để tránh xung đột
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Dimensions,
  Image,
  ImageBackground,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

// Import các tài nguyên và dịch vụ
import FamilyConnectModal from "../../src/components/FamilyConnectModal";
import { auth, db } from "../../src/config/firebase";
import { NotificationService } from "../../src/services/NotificationService";
import {
  getWeather,
  getWeatherIcon,
  getWeatherName,
} from "../../src/utils/weatherService";

const { width } = Dimensions.get("window");

// Assets
const bgImage = require("../../assets/images/home_bg.png");
const avatarUrl = "https://i.pravatar.cc/150?img=60";

const weatherImages: any = {
  cloudy: require("../../assets/images/weather_cloudy.png"),
  rain_light: require("../../assets/images/weather_rain_light.png"),
  rain_heavy: require("../../assets/images/weather_rain_heavy.png"),
};

const getDayLabel = (dateString: string, index: number) => {
  if (index === 0) return "Hôm nay";
  const days = ["CN", "T2", "T3", "T4", "T5", "T6", "T7"];
  const date = new Date(dateString);
  return days[date.getDay()];
};

export default function RelativeHomeScreen() {
  const router = useRouter();

  // --- STATES DỮ LIỆU ---
  const [name, setName] = useState("Người thân");

  // States Thời tiết
  const [temp, setTemp] = useState(0);
  const [weatherType, setWeatherType] = useState("cloudy");
  const [weatherLabel, setWeatherLabel] = useState("Đang tải...");
  const [forecast, setForecast] = useState<any[]>([]);
  const [locationName, setLocationName] = useState("Đang xác định...");

  // States cho Kết nối gia đình
  const [showConnect, setShowConnect] = useState(false);
  const [myKey, setMyKey] = useState("");
  const [isFetchingKey, setIsFetchingKey] = useState(false);

  const [unreadCount, setUnreadCount] = useState(0);

  // --- 1. HÀM MỞ KẾT NỐI (LOGIC RIÊNG BIỆT) ---
  const handleOpenConnect = async () => {
    console.log("-----------------------------------------");
    console.log("[DEBUG] >>>> ĐÃ BẤM NÚT KẾT NỐI");

    const user = auth.currentUser;
    if (!user) {
      Alert.alert("Lỗi", "Vui lòng đăng nhập lại.");
      return;
    }

    setMyKey("");
    setShowConnect(true);
    setIsFetchingKey(true);

    try {
      const docRef = doc(db, "users", user.uid);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        const userData = docSnap.data();

        if (userData.privateKey) {
          // TRƯỜNG HỢP 1: ĐÃ CÓ KEY -> HIỂN THỊ LUÔN
          console.log("[DEBUG] ✅ Đã tìm thấy Key:", userData.privateKey);
          setMyKey(userData.privateKey);
        } else {
          // TRƯỜNG HỢP 2: THIẾU KEY (LỖI BẠN ĐANG GẶP) -> TỰ TẠO MỚI VÀ CẬP NHẬT DB
          console.log(
            "[DEBUG] 🛠 Phát hiện thiếu Key. Đang tự động tạo mới...",
          );

          const autoGeneratedKey = Math.random().toString(36).substring(2, 14); // Tạo mã ngẫu nhiên

          // Gửi lệnh cập nhật lên Firebase
          const { updateDoc } = await import("firebase/firestore"); // Import nhanh
          await updateDoc(docRef, { privateKey: autoGeneratedKey });

          console.log(
            "[DEBUG] ✅ Đã tự sửa lỗi và lưu Key mới:",
            autoGeneratedKey,
          );
          setMyKey(autoGeneratedKey);
        }
      } else {
        setMyKey("ERR_DOC_NOT_FOUND");
      }
    } catch (error) {
      console.log("[DEBUG] ❌ Lỗi kết nối:", error);
      setMyKey("ERR_NETWORK");
    } finally {
      setIsFetchingKey(false);
      console.log("-----------------------------------------");
    }
  };

  // --- 2. HÀM LOAD DỮ LIỆU NỀN (TÊN & THỜI TIẾT) ---
  useEffect(() => {
    const loadBackgroundData = async () => {
      // A. Lấy Tên (Chỉ lấy tên, không lấy Key)
      try {
        const savedName = await AsyncStorage.getItem("userName");
        if (savedName) setName(savedName);
      } catch (e) {}

      // B. Lấy Thời tiết (Độc lập hoàn toàn)
      try {
        let lat = 10.82;
        let lon = 106.63; // Default
        let cityName = "TP. Hồ Chí Minh";

        // Thử xin quyền (Fail thì thôi, dùng default)
        try {
          const { status } = await Location.requestForegroundPermissionsAsync();
          if (status === "granted") {
            const loc = await Location.getCurrentPositionAsync({});
            lat = loc.coords.latitude;
            lon = loc.coords.longitude;
            const addr = await Location.reverseGeocodeAsync({
              latitude: lat,
              longitude: lon,
            });
            if (addr[0])
              cityName = addr[0].district || addr[0].city || "Vị trí của bạn";
          }
        } catch (gpsError) {
          console.log("Lỗi GPS (Không ảnh hưởng App):", gpsError);
        }

        setLocationName(cityName);
        const wData = await getWeather(lat, lon);
        if (wData) {
          setTemp(Math.round(wData.current.temperature_2m));
          setWeatherType(getWeatherIcon(wData.current.weather_code));
          setWeatherLabel(getWeatherName(wData.current.weather_code));
          setForecast(
            wData.daily.time.slice(0, 3).map((t: any, i: number) => ({
              date: t,
              max: Math.round(wData.daily.temperature_2m_max[i]),
              icon: getWeatherIcon(wData.daily.weather_code[i]),
            })),
          );
        }
      } catch (e) {
        console.log("Lỗi thời tiết:", e);
      }
    };

    loadBackgroundData();
  }, []);
  useEffect(() => {
    const user = auth.currentUser;
    if (!user) return;

    // Lắng nghe realtime collection "notifications" của user đó
    const q = query(
      collection(db, "users", user.uid, "notifications"),
      where("isRead", "==", false), // Chỉ đếm cái chưa đọc
    );

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        setUnreadCount(snapshot.size); // Cập nhật số lượng
      },
      (error) => {
        console.log("Lỗi badge:", error);
      },
    );

    return () => unsubscribe();
  }, []);
  const registerPushToken = async () => {
    const user = auth.currentUser;
    if (user) {
      const token =
        await NotificationService.registerForPushNotificationsAsync();
      if (token) {
        // Lưu token vào mảng fcmTokens (dùng arrayUnion để không bị trùng)
        const userRef = doc(db, "users", user.uid);
        await updateDoc(userRef, {
          fcmTokens: arrayUnion(token),
          lastLoginAt: serverTimestamp(), // Cập nhật giờ online
        });
      }
    }
  };
  registerPushToken();

  const ActionCard = ({ icon, title, subtitle, onPress }: any) => (
    <TouchableOpacity
      style={styles.actionCard}
      onPress={onPress}
      activeOpacity={0.85}
    >
      <View style={styles.actionIconCircle}>
        <Ionicons name={icon} size={26} color="#0055aa" />
      </View>
      <View>
        <Text style={styles.actionTitle}>{title}</Text>
        <Text style={styles.actionSub} numberOfLines={2}>
          {subtitle}
        </Text>
      </View>
      <View style={styles.cardArrow}>
        <Ionicons
          name="chevron-forward"
          size={16}
          color="rgba(255,255,255,0.7)"
        />
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={{ flex: 1 }}>
      <ImageBackground
        source={bgImage}
        style={styles.background}
        resizeMode="cover"
      >
        <SafeAreaView style={styles.safeArea} edges={["top"]}>
          {/* HEADER */}
          <View style={styles.header}>
            <View style={styles.userInfo}>
              <Image source={{ uri: avatarUrl }} style={styles.avatar} />
              <View>
                <Text style={styles.greeting}>Chào buổi sáng</Text>
                <Text style={styles.userName}>{name}</Text>
              </View>
            </View>
            <View style={styles.headerIcons}>
              {/* NÚT 4 Ô VUÔNG - GẮN HÀM MỚI Ở ĐÂY */}
              <TouchableOpacity
                style={styles.iconBtn}
                onPress={handleOpenConnect}
              >
                <Ionicons name="grid-outline" size={24} color="#0055aa" />
              </TouchableOpacity>

              {/* NÚT THÔNG BÁO ĐÃ ĐƯỢC NÂNG CẤP */}
              <TouchableOpacity
                style={styles.iconBtn}
                onPress={() => router.push("/notifications")}
              >
                <Ionicons
                  name="notifications-outline"
                  size={24}
                  color="#0055aa"
                />

                {/* HIỂN THỊ CHẤM ĐỎ NẾU CÓ THÔNG BÁO */}
                {unreadCount > 0 && (
                  <View style={styles.badge}>
                    <Text style={styles.badgeText}>
                      {unreadCount > 9 ? "9+" : unreadCount}
                    </Text>
                  </View>
                )}
              </TouchableOpacity>
            </View>
          </View>

          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={{ paddingBottom: 120 }}
          >
            {/* THẺ THỜI TIẾT */}
            <LinearGradient
              colors={["#007AFF", "#0055aa"]}
              style={styles.weatherCard}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
            >
              <View style={styles.weatherInfo}>
                <Text style={styles.tempText}>{temp}°</Text>
                <Text style={styles.tempRange}>
                  H:{forecast[0]?.max || temp + 2}° L:{temp - 2}°
                </Text>
                <Text style={styles.location}>{locationName}</Text>
              </View>
              <View style={styles.weatherVisual}>
                <Image
                  source={weatherImages[weatherType] || weatherImages.cloudy}
                  style={styles.weatherIconMain}
                  resizeMode="contain"
                />
                <Text style={styles.weatherCondition}>{weatherLabel}</Text>
              </View>
            </LinearGradient>

            {/* DỰ BÁO */}
            <Text style={styles.sectionTitleSmall}>Dự báo 3 ngày</Text>
            <View style={styles.forecastRow}>
              {forecast.length > 0 ? (
                forecast.map((day, index) => (
                  <View key={index} style={styles.forecastItem}>
                    <Image
                      source={weatherImages[day.icon]}
                      style={styles.smallWeatherIcon}
                      resizeMode="contain"
                    />
                    <Text style={styles.forecastTemp}>{day.max}°</Text>
                    <Text style={styles.forecastDay}>
                      {getDayLabel(day.date, index)}
                    </Text>
                  </View>
                ))
              ) : (
                <View style={{ padding: 20 }}>
                  <ActivityIndicator color="#0088cc" />
                </View>
              )}
            </View>

            {/* BANNER PREMIUM */}
            <LinearGradient
              colors={["#2c3e50", "#4ca1af"]}
              style={styles.premiumCard}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
            >
              <View style={{ flex: 1 }}>
                <View
                  style={{ flexDirection: "row", alignItems: "center", gap: 5 }}
                >
                  <Ionicons name="star" size={18} color="#FFD700" />
                  <Text style={styles.premTitle}>NÂNG CẤP PREMIUM</Text>
                </View>
                <Text style={styles.premSub}>Mở khóa tính năng cao cấp</Text>
              </View>
              <TouchableOpacity style={styles.premBtn}>
                <Text style={styles.premBtnText}>Khám phá</Text>
              </TouchableOpacity>
            </LinearGradient>

            {/* GRID CHỨC NĂNG */}
            <Text style={styles.sectionTitle}>Thao tác nhanh</Text>
            <View style={styles.gridContainer}>
              <ActionCard
                icon="camera-outline"
                title="Camera"
                subtitle="Giám sát và video"
                onPress={() => router.push("/camera-monitor")}
              />
              <ActionCard
                icon="stats-chart-outline"
                title="Báo cáo"
                subtitle="Thống kê chi tiết"
                onPress={() => router.push("/(relative-tabs)/reports")}
              />
              <ActionCard
                icon="medkit-outline"
                title="Thuốc"
                subtitle="Quản lý thuốc"
                onPress={() => router.push("/medicine-management")}
              />
              <ActionCard
                icon="add-circle-outline"
                title="Tạo nhắc nhở"
                subtitle="Thêm nhắc nhở cho người già"
                onPress={() => router.push("/create-reminder")}
              />
            </View>
          </ScrollView>
        </SafeAreaView>
      </ImageBackground>

      {/* MODAL KẾT NỐI */}
      <FamilyConnectModal
        visible={showConnect}
        onClose={() => {
          setShowConnect(false);
          setMyKey("");
        }}
        myPrivateKey={myKey}
        isLoading={isFetchingKey}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  background: { flex: 1, width: "100%", height: "100%", position: "absolute" },
  safeArea: { flex: 1 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 10,
    alignItems: "center",
  },
  userInfo: { flexDirection: "row", alignItems: "center", gap: 10 },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "white",
  },
  greeting: { color: "#666", fontSize: 14 },
  userName: { color: "#0055aa", fontSize: 18, fontWeight: "bold" },
  headerIcons: { flexDirection: "row", gap: 10 },
  iconBtn: {
    backgroundColor: "white",
    padding: 8,
    borderRadius: 20,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  weatherCard: {
    margin: 20,
    borderRadius: 25,
    padding: 25,
    flexDirection: "row",
    justifyContent: "space-between",
    height: 180,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  weatherInfo: { justifyContent: "space-between" },
  tempText: { fontSize: 60, color: "white", fontWeight: "bold" },
  tempRange: { color: "white", fontSize: 14, opacity: 0.9 },
  location: { color: "white", fontSize: 18, fontWeight: "600" },
  weatherVisual: { alignItems: "center", justifyContent: "center", width: 140 },
  weatherIconMain: { width: 100, height: 100, marginBottom: 5 },
  weatherCondition: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  sectionTitleSmall: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginLeft: 20,
    marginBottom: 10,
  },
  forecastRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  forecastItem: {
    backgroundColor: "rgba(255,255,255,0.9)",
    width: "31%",
    borderRadius: 15,
    padding: 15,
    alignItems: "center",
    elevation: 3,
  },
  smallWeatherIcon: { width: 40, height: 40, marginBottom: 5 },
  forecastTemp: { fontSize: 20, fontWeight: "bold", color: "#333" },
  forecastDay: { color: "#666", fontSize: 14 },
  premiumCard: {
    marginHorizontal: 20,
    marginBottom: 30,
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  premTitle: { color: "white", fontWeight: "bold", fontSize: 14 },
  premSub: { color: "#dbeafe", fontSize: 12, marginTop: 5 },
  premBtn: {
    backgroundColor: "white",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 12,
  },
  premBtnText: { color: "#1e40af", fontWeight: "bold", fontSize: 13 },
  sectionTitle: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: "#0055aa",
    marginBottom: 20,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  actionCard: {
    width: (width - 60) / 2,
    height: 160,
    backgroundColor: "#3b82f6",
    borderRadius: 25,
    padding: 15,
    marginBottom: 20,
    justifyContent: "space-between",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  actionIconCircle: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  actionTitle: {
    color: "white",
    fontWeight: "bold",
    fontSize: 18,
    marginTop: 10,
  },
  actionSub: { color: "rgba(255,255,255,0.8)", fontSize: 12, marginTop: 4 },
  cardArrow: { alignSelf: "flex-end" },
  badge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#FF3B30",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "white",
    zIndex: 10,
  },
  badgeText: {
    color: "white",
    fontSize: 9,
    fontWeight: "bold",
  },
});
